/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PastPapersRouteImport } from './routes/past-papers'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveClassesRouteImport } from './routes/live-classes'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherTestsRouteImport } from './routes/teacher.tests'
import { Route as TeacherResourcesRouteImport } from './routes/teacher.resources'
import { Route as TeacherNotesRouteImport } from './routes/teacher.notes'
import { Route as TeacherLiveClassesRouteImport } from './routes/teacher.live-classes'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher.assignments'
import { Route as TeacherAnnouncementsRouteImport } from './routes/teacher.announcements'
import { Route as DashboardPhysicsRouteImport } from './routes/dashboard.physics'
import { Route as DashboardChemistryRouteImport } from './routes/dashboard.chemistry'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestsRouteImport } from './routes/admin.tests'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminResourcesRouteImport } from './routes/admin.resources'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLiveClassesRouteImport } from './routes/admin.live-classes'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminConnectedAccountsRouteImport } from './routes/admin.connected-accounts'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAccessRequestsRouteImport } from './routes/admin.access-requests'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/student.courses.$courseId'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin.courses_.$courseId'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PastPapersRoute = PastPapersRouteImport.update({
  id: '/past-papers',
  path: '/past-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClassesRoute = LiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherTestsRoute = TeacherTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResourcesRoute = TeacherResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNotesRoute = TeacherNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLiveClassesRoute = TeacherLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnnouncementsRoute = TeacherAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => TeacherRoute,
} as any)
const DashboardPhysicsRoute = DashboardPhysicsRouteImport.update({
  id: '/physics',
  path: '/physics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChemistryRoute = DashboardChemistryRouteImport.update({
  id: '/chemistry',
  path: '/chemistry',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestsRoute = AdminTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesRoute = AdminResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveClassesRoute = AdminLiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectedAccountsRoute = AdminConnectedAccountsRouteImport.update({
  id: '/connected-accounts',
  path: '/connected-accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRequestsRoute = AdminAccessRequestsRouteImport.update({
  id: '/access-requests',
  path: '/access-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses_/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/live-classes': typeof LiveClassesRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/past-papers': typeof PastPapersRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/tests': typeof TestsRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/connected-accounts': typeof AdminConnectedAccountsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/live-classes': typeof AdminLiveClassesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tests': typeof AdminTestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/chemistry': typeof DashboardChemistryRoute
  '/dashboard/physics': typeof DashboardPhysicsRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/live-classes': typeof TeacherLiveClassesRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/tests': typeof TeacherTestsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/assignments': typeof AssignmentsRoute
  '/forbidden': typeof ForbiddenRoute
  '/live-classes': typeof LiveClassesRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/past-papers': typeof PastPapersRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/tests': typeof TestsRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/connected-accounts': typeof AdminConnectedAccountsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/live-classes': typeof AdminLiveClassesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tests': typeof AdminTestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/chemistry': typeof DashboardChemistryRoute
  '/dashboard/physics': typeof DashboardPhysicsRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/live-classes': typeof TeacherLiveClassesRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/tests': typeof TeacherTestsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/live-classes': typeof LiveClassesRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/past-papers': typeof PastPapersRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/tests': typeof TestsRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/access-requests': typeof AdminAccessRequestsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/connected-accounts': typeof AdminConnectedAccountsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/live-classes': typeof AdminLiveClassesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/resources': typeof AdminResourcesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/tests': typeof AdminTestsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/chemistry': typeof DashboardChemistryRoute
  '/dashboard/physics': typeof DashboardPhysicsRoute
  '/teacher/announcements': typeof TeacherAnnouncementsRoute
  '/teacher/assignments': typeof TeacherAssignmentsRoute
  '/teacher/live-classes': typeof TeacherLiveClassesRoute
  '/teacher/notes': typeof TeacherNotesRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/tests': typeof TeacherTestsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/courses_/$courseId': typeof AdminCoursesCourseIdRoute
  '/student/courses/$courseId': typeof StudentCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/assignments'
    | '/dashboard'
    | '/forbidden'
    | '/live-classes'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/past-papers'
    | '/profile'
    | '/schedule'
    | '/student'
    | '/teacher'
    | '/tests'
    | '/admin/access'
    | '/admin/access-requests'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/connected-accounts'
    | '/admin/courses'
    | '/admin/live-classes'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/resources'
    | '/admin/students'
    | '/admin/tests'
    | '/admin/users'
    | '/dashboard/chemistry'
    | '/dashboard/physics'
    | '/teacher/announcements'
    | '/teacher/assignments'
    | '/teacher/live-classes'
    | '/teacher/notes'
    | '/teacher/resources'
    | '/teacher/tests'
    | '/admin/'
    | '/dashboard/'
    | '/student/'
    | '/teacher/'
    | '/admin/courses/$courseId'
    | '/student/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/assignments'
    | '/forbidden'
    | '/live-classes'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/past-papers'
    | '/profile'
    | '/schedule'
    | '/tests'
    | '/admin/access'
    | '/admin/access-requests'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/connected-accounts'
    | '/admin/courses'
    | '/admin/live-classes'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/resources'
    | '/admin/students'
    | '/admin/tests'
    | '/admin/users'
    | '/dashboard/chemistry'
    | '/dashboard/physics'
    | '/teacher/announcements'
    | '/teacher/assignments'
    | '/teacher/live-classes'
    | '/teacher/notes'
    | '/teacher/resources'
    | '/teacher/tests'
    | '/admin'
    | '/dashboard'
    | '/student'
    | '/teacher'
    | '/admin/courses/$courseId'
    | '/student/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/assignments'
    | '/dashboard'
    | '/forbidden'
    | '/live-classes'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/past-papers'
    | '/profile'
    | '/schedule'
    | '/student'
    | '/teacher'
    | '/tests'
    | '/admin/access'
    | '/admin/access-requests'
    | '/admin/announcements'
    | '/admin/assignments'
    | '/admin/connected-accounts'
    | '/admin/courses'
    | '/admin/live-classes'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/resources'
    | '/admin/students'
    | '/admin/tests'
    | '/admin/users'
    | '/dashboard/chemistry'
    | '/dashboard/physics'
    | '/teacher/announcements'
    | '/teacher/assignments'
    | '/teacher/live-classes'
    | '/teacher/notes'
    | '/teacher/resources'
    | '/teacher/tests'
    | '/admin/'
    | '/dashboard/'
    | '/student/'
    | '/teacher/'
    | '/admin/courses_/$courseId'
    | '/student/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LiveClassesRoute: typeof LiveClassesRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  PastPapersRoute: typeof PastPapersRoute
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
  TestsRoute: typeof TestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-papers': {
      id: '/past-papers'
      path: '/past-papers'
      fullPath: '/past-papers'
      preLoaderRoute: typeof PastPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-classes': {
      id: '/live-classes'
      path: '/live-classes'
      fullPath: '/live-classes'
      preLoaderRoute: typeof LiveClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/tests': {
      id: '/teacher/tests'
      path: '/tests'
      fullPath: '/teacher/tests'
      preLoaderRoute: typeof TeacherTestsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/resources': {
      id: '/teacher/resources'
      path: '/resources'
      fullPath: '/teacher/resources'
      preLoaderRoute: typeof TeacherResourcesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notes': {
      id: '/teacher/notes'
      path: '/notes'
      fullPath: '/teacher/notes'
      preLoaderRoute: typeof TeacherNotesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/live-classes': {
      id: '/teacher/live-classes'
      path: '/live-classes'
      fullPath: '/teacher/live-classes'
      preLoaderRoute: typeof TeacherLiveClassesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/assignments': {
      id: '/teacher/assignments'
      path: '/assignments'
      fullPath: '/teacher/assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/announcements': {
      id: '/teacher/announcements'
      path: '/announcements'
      fullPath: '/teacher/announcements'
      preLoaderRoute: typeof TeacherAnnouncementsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/dashboard/physics': {
      id: '/dashboard/physics'
      path: '/physics'
      fullPath: '/dashboard/physics'
      preLoaderRoute: typeof DashboardPhysicsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chemistry': {
      id: '/dashboard/chemistry'
      path: '/chemistry'
      fullPath: '/dashboard/chemistry'
      preLoaderRoute: typeof DashboardChemistryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tests': {
      id: '/admin/tests'
      path: '/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources': {
      id: '/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AdminResourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-classes': {
      id: '/admin/live-classes'
      path: '/live-classes'
      fullPath: '/admin/live-classes'
      preLoaderRoute: typeof AdminLiveClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connected-accounts': {
      id: '/admin/connected-accounts'
      path: '/connected-accounts'
      fullPath: '/admin/connected-accounts'
      preLoaderRoute: typeof AdminConnectedAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access-requests': {
      id: '/admin/access-requests'
      path: '/access-requests'
      fullPath: '/admin/access-requests'
      preLoaderRoute: typeof AdminAccessRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/courses/$courseId': {
      id: '/student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/courses_/$courseId': {
      id: '/admin/courses_/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminAccessRequestsRoute: typeof AdminAccessRequestsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminConnectedAccountsRoute: typeof AdminConnectedAccountsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminLiveClassesRoute: typeof AdminLiveClassesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminResourcesRoute: typeof AdminResourcesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTestsRoute: typeof AdminTestsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminAccessRequestsRoute: AdminAccessRequestsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminConnectedAccountsRoute: AdminConnectedAccountsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminLiveClassesRoute: AdminLiveClassesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminResourcesRoute: AdminResourcesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTestsRoute: AdminTestsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardChemistryRoute: typeof DashboardChemistryRoute
  DashboardPhysicsRoute: typeof DashboardPhysicsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChemistryRoute: DashboardChemistryRoute,
  DashboardPhysicsRoute: DashboardPhysicsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface StudentRouteChildren {
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentIndexRoute: StudentIndexRoute,
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAnnouncementsRoute: typeof TeacherAnnouncementsRoute
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  TeacherLiveClassesRoute: typeof TeacherLiveClassesRoute
  TeacherNotesRoute: typeof TeacherNotesRoute
  TeacherResourcesRoute: typeof TeacherResourcesRoute
  TeacherTestsRoute: typeof TeacherTestsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnnouncementsRoute: TeacherAnnouncementsRoute,
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  TeacherLiveClassesRoute: TeacherLiveClassesRoute,
  TeacherNotesRoute: TeacherNotesRoute,
  TeacherResourcesRoute: TeacherResourcesRoute,
  TeacherTestsRoute: TeacherTestsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  AssignmentsRoute: AssignmentsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LiveClassesRoute: LiveClassesRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  PastPapersRoute: PastPapersRoute,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
  TestsRoute: TestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
